name: PR Validate

on:
  pull_request:
    types: [edited, opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-edit-${{ github.event.number }}
  cancel-in-progress: true
permissions: {}
jobs:
  validate:
    name: Validate PR
    if: (! github.event.pull_request.draft)
    runs-on: ubuntu-24.04
    permissions:
      contents: read          # Required for repository access
      pull-requests: write    # Required for commenting on PRs
    steps:
      - uses: bcgov/actions/pr-validate@c4694d429e6c8025974ba383f6f26ff8a41f7755 # v0.7.1
        with:
          add_markdown: |
            - [Java](https://${{ github.event.repository.name }}-${{ github.event.number }}-backend-java.apps.silver.devops.gov.bc.ca)
            - [Py](https://${{ github.event.repository.name }}-${{ github.event.number }}-backend-py.apps.silver.devops.gov.bc.ca)

  results:
    name: Validate Results
    if: always()
    needs: [validate]
    runs-on: ubuntu-24.04
    steps:
      - uses: bcgov/actions/workflow-results@c4694d429e6c8025974ba383f6f26ff8a41f7755 # v0.7.1
        with:
          needs: ${{ toJson(needs) }}
          title: "Validate Results"
